### ISSUE TITLE
Respects ssh_options[:port] but not just plain :port

### ISSUE THREAD

**Issue by boutell** [vigetlabs/capistrano_rsync_with_remote_cache#10]
The rest of capistrano seems to respect this:

set :port, 66666

But the rsync gem does not. Eventually I figured out this was supported by both by looking at the source:

ssh_options[:port] = 22123

Thanks for the rsync gem!

**Comment by reagent** [comment]
Fixed in [this commit](https://github.com/vigetlabs/capistrano_rsync_with_remote_cache/commit/efa403ddd9ef021333aff38d9169db546ac99f58) -- pushing out a new release in the next couple weeks after I close out all remaining PRs / issues.
