### ISSUE TITLE
Configurable rsync exclusions

### ISSUE THREAD

**Issue by nnevala** [vigetlabs/capistrano_rsync_with_remote_cache#21]
It would be tremendously useful to have a configuration option for paths that would be excluded from the rsync.

**Comment by fstrube** [comment]
Rsync has a couple of options for excluding, although I would recommend at least using the --exclude-from option. See http://linux.die.net/man/1/rsync.

**Comment by reagent** [comment]
Looks like this is addressed in #26. Looking into it.

**Comment by reagent** [comment]
I'm using [`--exclude` with `--delete-excluded` to achieve this](https://github.com/vigetlabs/capistrano_rsync_with_remote_cache/commit/4c19355ba6bcbb7dccb72a8ee6bcd04691533d4a).  You'll just need to set the `:copy_exclude` variable in your deploy configuration.
