### ISSUE TITLE
Is this project deprecated / not maintened anymore ?

### ISSUE THREAD

**Issue by joksnet** [vigetlabs/capistrano_rsync_with_remote_cache#27]
There are some three years old pull request that are still not merged. /cc @vigetlabs @reagent @markcornick

**Comment by mcornick** [comment]
@joksnet I left Viget Labs in 2009 and no longer work on this repo.

**Comment by reagent** [comment]
Hey @joksnet -- I'll take a look at the outstanding PRs and look at pushing a new version this week.

**Comment by joksnet** [comment]
@reagent Bump.

**Comment by Gonzih** [comment]
any updates?

**Comment by reagent** [comment]
Finally getting back to this -- will start triaging issues next week.

**Comment by reagent** [comment]
Just [updated dependencies and tests](https://github.com/vigetlabs/capistrano_rsync_with_remote_cache/commit/6cc31db2e67c637b6bfedf41f87d01fd912b8f98) and am starting to work through the backlog of PRs / issues.

**Comment by joksnet** [comment]
I'm not using it anymore. Closing the issue.
