### ISSUE TITLE
scm :none

### ISSUE THREAD

**Issue by MagnaTr0n** [vigetlabs/capistrano_rsync_with_remote_cache#3]
I do not use scm most of my capistrano-stuff because the local_cache are compiled classes.
I got an error when using scm : none...
wrapping the "local cache update" fixed it...

```
     # Step 1: Update the local cache.
      if configuration[:scm] != :none
        system(command)
        File.open(File.join(local_cache, "REVISION"), "w") { |file| file.puts(revision) }
      end
```

If it does not break stuff for you i would love to have it included in the project because then i could just use your gem without changing it..
Many thanks Magnus.
maghansen@gmail.com

**Comment by reagent** [comment]
Hey.  I just took over maintenance of this project and wanted to address this (sorry for the delay).  Is there a reason you can't use the built-in `deploy_via :copy` strategy?

http://www.capify.org/index.php/Understanding_Deployment_Strategies#Deploy_Strategy_:copy
