### ISSUE TITLE
server-specific ssh port not used

### ISSUE THREAD

**Issue by sbfaulkner** [vigetlabs/capistrano_rsync_with_remote_cache#4]
when a server is configured to use a different ssh port on a server by server basis it is not used for the rsync

**Comment by sbfaulkner** [comment]
fixed in my fork:
http://github.com/sbfaulkner/capistrano_rsync_with_remote_cache/commit/ae6db7a94885b72d93aa5bcdedf323f77f42de48

**Comment by reagent** [comment]
Can you give me an example configuration that exposes this problem?  I may need to re-think how the port config is generated.

**Comment by sbfaulkner** [comment]
We've got a cluster on a network outside of our network that is behind a load-balancer. The servers share a single external IP address, so we deploy to the two servers using ssh running on a different port on each node of the cluster.

We're actually using webistrano (rather than capistrano), but the exported capfile includes the following...

```
role :app, "server.example.com:56009"
role :app, "server.example.com:56010"
role :db, "server.example.com:56009", {:primary=>true}
role :db, "server.example.com:56010"
role :web, "server.example.com:56009"
role :web, "server.example.com:56010"
```

Does the patch I proposed introduce a problem?

**Comment by reagent** [comment]
> Does the patch I proposed introduce a problem?

I don't think so, I just thought that your use-case may have introduced a more efficient way of handling the SSH config instead of supplying a different port via `set :ssh_options`.  I may deprecate that global option in favor of your solution - I'll have to think about it.

At any rate - I'll pull this in this week. Thanks!

**Comment by sbfaulkner** [comment]
I don't think you want to deprecate it... we do have other servers we deploy to where it is far more convenient to use the global option.

**Comment by reagent** [comment]
Took me forever, but your changes are in there: http://github.com/vigetlabs/capistrano_rsync_with_remote_cache/tree/2.4.0

Gem is published too: http://rubygems.org/gems/capistrano_rsync_with_remote_cache

**Comment by sbfaulkner** [comment]
cheers
